---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jolie-deployer
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jolie-deployer
    spec:
      containers:
        - image: "dm848/srv-jolie-deployer:v1.0.6"
          imagePullPolicy: Always
          name: jolie-deployer
          ports:
            - containerPort: 8000
          env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: jolie-deployer
  namespace: "default"
  labels:
    app: jolie-deployer
spec:
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
  selector:
    app: jolie-deployer
